# Generated by Django 6.0.7 on 2026-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=20)),
                ("msg_text", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(verbose_name="message timestamp")),
            ],
        ),
    ]
